name: test build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Configure project name
        id: config_project
        run: |
          echo "NAME=$(cat ./_config_project.yml | grep -e '^project_name: .*$' | sed -e 's/project_name: //g')" >> $GITHUB_OUTPUT

      - name: Configure module name
        id: config_module
        run: |
          proj_name="${{ steps.config_project.outputs.NAME }}"
          echo "NAME=${proj_name,,}" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Restore cache for Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build project with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-build-artifacts-${{ github.run_number }}
          path: |
            ./${{ steps.config_module.outputs.NAME }}/build/outputs/aar/*.aar
          retention-days: 1
